config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users, only: [:show]
  get 'profiles', to: 'profiles#show'
  #get    "users",          to: "users#profile"
  resources :flats  do
    resources :appointments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  validates :status, inclusion: { in: ["Approved", "Rejected", "Pending"] }
  validates :date, presence: true
  validates :time, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  validates :title, uniqueness: true, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :number_of_rooms, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flats
  has_many :appointments
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :set_dates, only: :create
  before_action :authenticate_user!
   # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    private

    def set_dates
      if params[:controller] =~ /.*appointments.*/
        session[:time] = params[:appointment][:time]
        session[:date] = params[:appointment][:date]
      end
    end

    def storable_location?
      is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.referer)
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    set_user
    @appointments = Appointment.where(flat_id: params[:flat_id])
  end

  def new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    # we need `flat_id` to asssociate appointment with corresponding restaurant
    @appointment.flat = Flat.find(params[:flat_id])
    @appointment.user = current_user
    @appointment.status = "Pending"

    if @appointment.save
      redirect_to flat_path(@appointment.flat)
    else
      render :new
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @flat = @appointment.flat
    @appointment.destroy
    redirect_to profiles_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :time, :flat_id, :user_id, :status)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    flat_aux = Flat.near(params["query"]["address"].split("/")[0] , 15)

    if params[:query]["address"].split("/")[1].nil?
    @flats = flat_aux.where(price: params[:query][:min_price]..params[:query][:max_price]  )
      else
    @flats = flat_aux.where(price: params[:query]["address"].split("/")[1]..params[:query]["address"].split("/")[2]  )
    end

    @markers = @flats.map do |flat|
      {
        lng: flat.longitude,
        lat: flat.latitude,
        infoWindow: { content: render_to_string(partial: "/flats/map_window", locals: { flat: flat }) }
      }
    end
  end

  def show
    if !params[:format].nil?
      if params[:format].split("/").size == 2
      aux = params[:format].split("/")
      appoint = Appointment.find(aux[0].to_i)
      appoint.status = aux[1]
      appoint.save
      end
    end
    @appointments = @flat.appointments

    @appointment = Appointment.new
    if session[:date] && session[:time]
      # raise
      @appointment.date = session[:date]
      @appointment.time = session[:time]
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    user_aux = User.find(current_user.id)
    user_aux.seller = true
    user_aux.save
    @flat = Flat.new(flat_params)
    if !flat_params[:photo]
      @flat.remote_photo_url = "https://urbangauge.com/wp-content/uploads/2018/06/flat-768x384.jpg"
    end
    current_user.seller = true
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to profiles_path
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to profiles_path
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :price, :address, :description, :number_of_rooms, :photo, :user_id)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    set_user
    @flats = Flat.where(user_id: @user.id)
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<h1>Appointmentss</h1>

<%@appointments.each do |appointment| %>
<ul>
  <li><%= User.where(id: appointment.user_id).first.email %></li>
  <li><%=appointment.time%></li>
  <li><%=appointment.date%></li>
  <li><%=appointment.status%></li>
    <li><%= link_to "Delete appointment", flat_appointment_path(appointment.flat, appointment),
     method: :delete,
     data: { confirm: "Are you sure?" } %></li>
</ul>
<% end %>

app/views/appointments/new.html.erb
<h5> Your appointment is the <%= params[:appointment][:time] %></h5>

<%= simple_form_for [@appointment.flat, @appointment] do |f| %>
  <%= f.input :date  %>
  <%= f.input :time %>
  <%= f.submit "Confirm appointment", class: "btn btn-primary" %>
<% end %>

app/views/flats/_map_window.html.erb
<%= flat.title %>
<%= flat.address %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="add-form center-block">
    <%= simple_form_for [@flat] do |f| %>
    <%= f.input :title %>
    <%= f.input :address, :input_html => {
          :id => "flat_address"
        } %>
    <%= f.input :price, as: :integer %>
    <%= f.input :description %>
    <%= f.input :number_of_rooms, as: :numeric %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Edit", class: "btn btn-primary bigger" %>
  <% end %>
  <%= link_to "Back to your profile", profiles_path, class:"back-homepage" %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="body">
  <div class="cards">
    <div class="row">
      <%@flats.each do |flat| %>
        <div class="col-xs-12 col-sm-6">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path flat.photo, height: 300, width: 400, crop: :fill %>')">
            <div class="card-description">
              <h2><%= link_to flat.title, flat_path(flat, address: [params[:query][:address], min_price: params[:query][:min_price], max_price: params[:query][:max_price]]) %></h2>
              <p>Address: <%= flat.address %> | Rooms: <%= flat.number_of_rooms %></p>
            </div>
            <div class="card-price">
              <p><%= number_to_currency(flat.price,unit: "€",precision: 0, format: "%n %u", delimiter: ".") %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="add-form center-block">
    <%= simple_form_for [@flat] do |f| %>
    <%= f.input :title %>
    <%= f.input :address, :input_html => {
          :id => "flat_address"
        } %>
    <%= f.input :price, as: :integer %>
    <%= f.input :description %>
    <%= f.input :number_of_rooms, as: :numeric %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add", class: "btn btn-primary bigger" %>
  <% end %>
  <%= link_to "Back to the home page", root_path, class:"back-homepage" %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
<div class="flat-container">
  <div class="flat-information">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <div class="flat-image">
        <%= cl_image_tag @flat.photo, height: 200, width: 300, crop: :fill%>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="flat-details">
        <div class="flat-title">
          <h2><strong><%=@flat.title.capitalize%></strong></h2>
          <p><%=@flat.description%></p>
        </div>
        <div class="flat-address">
          <p>Address: <%= @flat.address %> | Rooms: <%= @flat.number_of_rooms %></p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-3">
     <div class="flat-price">
      <div class="price-info">
      <p><%=number_to_currency(@flat.price,unit: "€",precision: 0, format: "%n %u", delimiter: ".")%></p>
    </div>
    </div>
  </div>
  </div>
</div>

<% if !params[:format].nil? %>
  <% if params[:format].split("/").size != 2%>
    <%= link_to "Back to the search", flats_path(query:{address: params[:format]}), class: "btn btn-success small-text" %>
  <% end  %>
<% end %>


<% if @flat.user == current_user && @appointments.count != 0 %>
<h3>Appointmentss</h3>



<%@appointments.each do |appointment| %>

<div class="message center-block" >
  <div class="message-name">
    <p><%= User.where(id: appointment.user_id).first.email %></p>
  </div>
  <div class="message-body">
    <p> <%= "#{appointment.date}, #{appointment.time.strftime('at %I:%M%p')}"  %> </p>
  </div>
  <div class="message-status">

  <div class="dropdown">
      <% if appointment.status == "Pending" %>
      <p class="status pending", data-toggle="dropdown"><%=appointment.status%></p>
      <% elsif  appointment.status == "Approved" %>
      <p class="status accepted", data-toggle="dropdown"><%=appointment.status%></p>
      <%  else  %>
      <p class="status declined", data-toggle="dropdown"><%=appointment.status%></p>
      <% end  %>
        <ul class="dropdown-menu">
   <li ><%= link_to "Make pending", flat_path(appointment.flat, [appointment.id, "Pending"]) %> </li>
   <li ><%= link_to "Accept it", flat_path(appointment.flat, [appointment.id, "Approved"]) %> </li>
   <li><%= link_to "Reject it", flat_path(appointment.flat, [appointment.id, "Rejected"]) %> </li>
   </ul>
      </div>

  </div>
</div>
<% end %>
<% end %>


<% if @flat.user != current_user %>
  <div class="call-to-action" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path("n5notsnugb6t3ghtfkdx.jpg") %>')">
    <div class="calendar" style="width: 400px; margin: 0 auto;">
      <h3 class="white-color">Add an appointment to visit...</h3>

      <%= simple_form_for [@flat, @appointment] do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :time, as: :string, required: false, input_html: {class: "timepicker"} %>
        <%= f.button :submit, "Add", class: "btn btn-success center-block bigger" %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>House</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title>Basic info</title>

  <!-- Google fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Montserrat:400,700">

  <!-- Fontawesome -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Your style -->
  <link rel="stylesheet" href="style.css">
</head>

<body>

  <div class="home-page"></div>
  <div class="homepage-container">

    <div class="hero-content">

      <div class="display-table">
        <div class="display-table-cell vertical-middle align-center">

          <h1 class="hero-strapline">Search properties for sale!</h1>


                <%= simple_form_for :query, method: :get, url: flats_path do |f| %>
                <%= f.input :address, label: false, placeholder: "Location", :input_html => { :id => "flat_address"} %>
                <div class="row"></div>

                <div class="form-group form-inline center-block">
                  <%= f.input :min_price, label: false, placeholder: "Min. Price" %>
                  <%= f.input :max_price, label: false, placeholder: "Max. Price" %>
                </div>

          <span><%= f.submit "Search", class: "btn btn-primary center-block" %></span>
          <% end %>

          <div class="pos-rel">
            <ul id="typeaheadList" class="type-ahead-list"></ul>

          </div>
        </div>
      </div>
    </div>




        <div class="cards-container">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="homepage-card" style="background-image:linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=20c4a4adf9bec9372a3d35e95b1d0eab&auto=format&fit=crop&w=800&q=60')">

                        <%=  link_to "Barcelona",  flats_path(query:{address: "Barcelona, Catalunya, Spain/0/100000000//"}), class:"btn-medium" %>

                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="homepage-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1539037116277-4db20889f2d4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f54fb1a766ab8a09c10b3a0ab62727f3&auto=format&fit=crop&w=1500&q=80')">

                       <%=  link_to "Madrid",  flats_path(query:{address: "Madrid, Comunidad de Madrid, Spain/0/100000000//"}), class:"btn-medium" %>

                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="homepage-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1542115015-16997067a9f4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f33f266e30636177c46d49941e0b0b56&auto=format&fit=crop&w=1336&q=80')">

                       <%=  link_to "Seville",  flats_path(query:{address: "Seville, Andalucía, Spain/0/100000000//"}), class:"btn-medium" %>

                </div>
            </div>
        </div>



  </body>
  </html>

app/views/profiles/show.html.erb
<div class="container">

    <% if current_user.flats.count != 0 %>
    <div class="flats-container">
        <h3>My ads</h3>
        <div class="cards">
            <div class="row">

                <%@flats.each do |flat| %>

                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="card-of-my-flat" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path flat.photo, height: 280, width: 400, crop: :fill %>')">
                        <div class="card-description">
                            <h2><%= link_to flat.title, flat_path(flat) %></h2>
                            <p>Address: <%= flat.address %> | Rooms: <%= flat.number_of_rooms %></p>
                        </div>
                        <p class="card-price"><%= number_to_currency(flat.price,unit: "€",precision: 0, format: "%n %u", delimiter: ".") %></p>
                    </div>

                    <div class="actions-container">
                        <div class="edit-card">
                            <p><%= link_to edit_flat_path(flat) do %>
                                <i class="fas fa-edit"></i>
                                <% end %> </p>
                                <p><%= link_to flat_path(flat),
                                method: :delete,
                                data: { confirm: "Are you sure?" } do  %>
                                <i class="fas fa-trash-alt"></i>
                                <% end %> </p>
                            </div>

                            <% if flat.appointments.where(status: "Pending").count > 0 %>

                            <div class="status-card red">
                                <p><%= link_to "Pending appointments: #{flat.appointments.where(status: "Pending").count}", flat_path(flat) %> </p>
                            </div>

                            <% else  %>

                            <div class="status-card">
                                <p><%= link_to "Pending appointments: #{flat.appointments.where(status: "Pending").count}", flat_path(flat) %> </p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <%end%>
                </div>
                <% end %>
            </div>
            <br>

            <%= link_to "Post your ad", new_flat_path, class: "btn btn-success padding" %>

            <% if current_user.appointments.count != 0 %>
            <div class="property-ad-container">
                <div class="row">
                    <div class="col-sm-12">
                        <h3>My appointments</h3>
                    </div>
                </div>
                <div class="row">
                    <%@user.appointments.each do |appointment| %>
                    <div class="col-xs-12 col-sm-6">
                        <div class="ad-card">
                            <div class="myappcard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1541604193435-22287d32c2c2?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=444ee2be04c2a4083a0aa214d910c27a&auto=format&fit=crop&w=1650&q=80')">
                            </div>
                            <div class="appointment-info">
                                <ul class="customize" style="font-weight:bold"> <%= link_to Flat.where(id: appointment.flat_id).first.title, flat_path(Flat.where(id: appointment.flat_id).first), class:"btn-button" %>
                                    <span class="status"><%= appointment.status %></span>
                                    <br>

                                    <li><%= "#{appointment.date}, #{appointment.time.strftime('at %I:%M%p')}"  %></li> <br>
                                    <li><%= link_to "Delete appointment", flat_appointment_path(appointment.flat, appointment),
                                    method: :delete,
                                    data: { confirm: "Are you sure?" } %> </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>


                <% end %>
            </div>

app/views/shared/_footer.html.erb
<div class="footer navbar-fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by Houseo!
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="https://res.cloudinary.com/doq7jkjo0/image/upload/v1543313488/Houseo/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <%= link_to "Place your ad here", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if current_user.nil? %>
    <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else  %>
    <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end  %>
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a> -->

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://res.cloudinary.com/doq7jkjo0/image/upload/v1543314369/Houseo/loginicon.png" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", profiles_path %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>
</nav>